name: Run e2e tests
on:
  schedule:
    - cron: '0 07 * * *'
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/build

      - uses: ./.github/actions/test
