name: build&test
on:
  schedule:
    - cron: '0 07 * * *'
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: build
        uses: ./.github/actions/build

      - name: run tests
        uses: ./.github/actions/test
