name: build&test
on:
  schedule:
    - cron: '0 07 * * *'
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/setup

      - name: lint
        shell: bash
        run: yarn lint

      - name: build
        uses: ./.github/actions/build

      - name: run unit tests
        shell: bash
        run: yarn test

      - name: run e2e tests
        uses: ./.github/actions/e2e-test
        env:
          E2E_PAT: ${{ secrets.E2E_PAT }}
