name: publish

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/setup

      - name: lint
        shell: bash
        run: yarn lint

      - name: build
        uses: ./.github/actions/build

      - name: run unit tests
        shell: bash
        run: yarn test

      - name: run e2e tests
        uses: ./.github/actions/e2e-test
        env:
          E2E_PAT: ${{ secrets.E2E_PAT }}

      - name: Install web-ext
        run: yarn global add web-ext

      - name: Publish firefox
        run: |
          web-ext sign \
            --source-dir "build/firefox-mv3-prod" \
            --api-key "${{ secrets.FIREFOX_STORE_JWT_ISSUER }}" \
            --api-secret "${{ secrets.FIREFOX_STORE_JWT_SECRET }}" \
            --channel "listed"

      - name: Install chrome webstore upload cli
        run: yarn global add chrome-webstore-upload-cli

      - name: Publish Chrome
        run: |
          chrome-webstore-upload \
            --source "build/chrome-mv3-prod" \
            --extension-id "${{ secrets.CHROME_STORE_EXTENSION_ID }}" \
            --client-id "${{ secrets.CHROME_STORE_CLIENT_ID }}" \
            --client-secret "${{ secrets.CHROME_STORE_CLIENT_SECRET }}" \
            --refresh-token "${{ secrets.CHROME_STORE_REFRESH_TOKEN }}"
